# Generated by Django 6.0.4 on 2026-04-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcheck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='dependency_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='downstream_dependency_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
