# Generated by Django 6.0.4 on 2026-04-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcheck', '0002_team_dependency_type_team_downstream_dependency_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='dependency_type',
        ),
        migrations.RemoveField(
            model_name='team',
            name='downstream_dependency_text',
        ),
        migrations.AddField(
            model_name='dependency',
            name='dependency_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
