# Generated by Django 6.0.4 on 2026-04-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcheck', '0003_remove_team_dependency_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependency',
            name='dependency_type',
        ),
        migrations.AddField(
            model_name='team',
            name='dependency_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='downstream_dependency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
